// ─────────────────────────────────────────────────────────────────────────────
// AroMatch Perfume Catalog — 22 items  (SINGLE SOURCE OF TRUTH)
// ─────────────────────────────────────────────────────────────────────────────

export interface Perfume {
  // Campos de display (UI)
  image: string
  brand: string
  name: string
  family: string
  match: string
  description: string
  exhaustiveDescription: string
  occasion: string
  longevity: string
  sillage: string
  season: string
  vibe: string
  topNotes: string[]
  heartNotes: string[]
  baseNotes: string[]
  notes: string[]
  sommelier: string

  // Campos de negocio
  costUSDT: number
  priceARS: number
  inStock: boolean
  deliveryDays: string
  tier: number
  mlSales: string
  gender: 'masculino' | 'femenino' | 'unisex'

  // Campos de matching (algoritmo)
  occasions: Array<'cita_nocturna' | 'oficina_diario' | 'evento_especial' | 'deporte_aire_libre'>
  seasons: Array<'summer' | 'winter' | 'spring' | 'fall'>
  scentStyle: Array<'dulce' | 'fresco' | 'maderoso' | 'especiado'>
  projections: Array<'moderate' | 'high' | 'beast'>
}

export interface MatchResult {
  perfume: Perfume
  score: number
  percentage: number
  matchReasons: string[]
}

export const perfumes: Perfume[] = [

  // ═══════════════════════════════════════════════════
  // TIER 1 — STOCK FÍSICO (inStock: true)
  // ═══════════════════════════════════════════════════

  {
    name: 'Khamrah',
    brand: 'Lattafa Perfumes',
    family: 'Oriental Gourmand',
    match: "El clon de Angels' Share de Kilian a 1/10 del precio.",
    description: 'Coñac, dátiles, canela y praline con base de vainilla suntuosa. El más compartido en redes. Calor y misterio en un frasco.',
    exhaustiveDescription: 'Khamrah ("Vino" en árabe) es la fragancia que viralizó TikTok perfumero. Su apertura de coñac y dátiles evoca las veladas más exclusivas de Dubái. El corazón de canela y praline añade calidez golosa sin cruzar hacia lo excesivamente dulce. La base de vainilla pura es una caricia sedosa.',
    sommelier: 'Khamrah es un perfume que no pide permiso. La canela y el praliné crean una oscuridad dulce que es imposible ignorar. Si alguna vez quisiste oler a whisky de lujo mezclado con un postre árabe, esto es exactamente eso. Beast Mode garantizado.',
    occasion: 'Noche · Eventos especiales',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Oscuro · Seductor · Hipnótico',
    image: '/perfumes/lattafa-kamrha.webp',
    topNotes: ['Canela', 'Nuez moscada', 'Bergamota'],
    heartNotes: ['Praliné', 'Dátiles', 'Tuberosa'],
    baseNotes: ['Vainilla', 'Haba tonka', 'Mirra'],
    notes: ['Canela', 'Praliné', 'Vainilla', 'Bergamota', 'Mirra'],
    costUSDT: 22.5,
    priceARS: 55000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+5000 vendidos ML AR',
    gender: 'unisex',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['winter', 'fall'],
    scentStyle: ['dulce', 'especiado'],
    projections: ['beast'],
  },

  {
    name: 'Yara Candy',
    brand: 'Lattafa Perfumes',
    family: 'Floral Frutal Gourmand',
    match: 'El perfume que genera halagos cada vez que lo usás.',
    description: 'Frutas confitadas, vainilla y malvavisco crean una explosión gourmand irresistible. La fragancia que conquista corazones en cualquier ambiente casual.',
    exhaustiveDescription: 'Yara Candy es el capricho olfativo más irresistible de Lattafa. Una construcción gourmand de alta joyería que combina frutas confitadas vibrantes con un corazón cremoso de vainilla artesanal y la suavidad aérea del malvavisco. Es una fragancia lúdica con refinamiento.',
    sommelier: 'Yara Candy es el favorito femenino árabe del momento. Dulce, frutal y adictivo — genera halagos desde la primera vez. El 100% de las personas que lo huelen preguntan qué es. Es el perfume que se compra una vez y se repone para siempre.',
    occasion: 'Día · Trabajo · Salidas',
    longevity: '8-10h',
    sillage: 'Alta',
    season: 'Primavera · Verano · Otoño',
    vibe: 'Dulce · Juguetón · Adictivo',
    image: '/perfumes/yara-candy.webp',
    topNotes: ['Grosella negra', 'Mandarina verde'],
    heartNotes: ['Gardenia', 'Fresa candy'],
    baseNotes: ['Vainilla', 'Almizcle', 'Ámbar'],
    notes: ['Grosella', 'Mandarina', 'Gardenia', 'Vainilla', 'Almizcle'],
    costUSDT: 23.5,
    priceARS: 52000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+5000 vendidos ML AR',
    gender: 'femenino',
    occasions: ['oficina_diario', 'evento_especial', 'deporte_aire_libre'],
    seasons: ['spring', 'summer', 'fall'],
    scentStyle: ['dulce'],
    projections: ['high'],
  },

  {
    name: 'Yara Rosa',
    brand: 'Lattafa Perfumes',
    family: 'Floral Frutal',
    match: 'El clásico árabe femenino. Versátil, elegante, para toda ocasión.',
    description: 'Heliotropo, mandarina, orquídea y notas tropicales con base de vainilla suave. La fragancia femenina viral.',
    exhaustiveDescription: 'Yara Rosa es la hermana más dulce de la casa. El heliotropo empolvado abre con una dulzura celestial. La mandarina añade chispa cítrica, mientras que la orquídea en su corazón proporciona un carácter decididamente exótico y vibrante.',
    sommelier: 'Yara Rosa es el número uno absoluto en ventas de perfumes árabes en Argentina. Floral, versátil y con una duración impresionante. Lo usás un martes y alguien te pregunta si vas a una fiesta. Compliment getter garantizado.',
    occasion: 'Día · Noche · Trabajo',
    longevity: '8-10h',
    sillage: 'Media-Alta',
    season: 'Todo el año',
    vibe: 'Floral · Elegante · Versátil',
    image: '/perfumes/yara-rosa.webp',
    topNotes: ['Durazno', 'Flor de cerezo', 'Bergamota'],
    heartNotes: ['Rosa', 'Jazmín', 'Iris'],
    baseNotes: ['Sándalo', 'Almizcle', 'Vainilla'],
    notes: ['Durazno', 'Rosa', 'Jazmín', 'Sándalo', 'Almizcle'],
    costUSDT: 24.5,
    priceARS: 52000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+10000 vendidos ML AR — 5° ranking general',
    gender: 'femenino',
    occasions: ['cita_nocturna', 'oficina_diario', 'evento_especial'],
    seasons: ['summer', 'winter', 'spring', 'fall'],
    scentStyle: ['dulce', 'fresco'],
    projections: ['moderate', 'high'],
  },

  {
    name: 'Mandarin Sky',
    brand: 'Armaf',
    family: 'Floral Frutal Gourmand',
    match: 'El 6° más vendido de toda la categoría perfumes en MercadoLibre Argentina.',
    description: 'Tropical y luminoso. Mandarina, piña y sándalo dorado.',
    exhaustiveDescription: 'Mandarin Sky es el resultado de poner un atardecer tropical en un frasco. La mandarina y la piña abren con una explosión de energía frutal que inmediatamente se transforma en algo más floral y sofisticado.',
    sommelier: 'Mandarin Sky es el 6° perfume más vendido de toda la categoría en Argentina — no solo árabe, sino todos. La mandarina y la piña tropical abren con energía inmediata, y la base de sándalo dorado crea una calidez irresistible. Es un estado de ánimo en frasco.',
    occasion: 'Día · Noche · Eventos',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Primavera · Verano · Otoño',
    vibe: 'Tropical · Luminoso · Optimista',
    image: '/perfumes/mandarin-sky.webp',
    topNotes: ['Mandarina', 'Piña tropical', 'Bergamota'],
    heartNotes: ['Flor de azahar', 'Jazmín', 'Rosa'],
    baseNotes: ['Sándalo dorado', 'Ámbar solar', 'Almizcle'],
    notes: ['Mandarina', 'Piña', 'Jazmín', 'Sándalo', 'Ámbar'],
    costUSDT: 29.3,
    priceARS: 57000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+10000 vendidos ML AR — 6° ranking general',
    gender: 'unisex',
    occasions: ['oficina_diario', 'evento_especial', 'cita_nocturna', 'deporte_aire_libre'],
    seasons: ['spring', 'summer', 'fall'],
    scentStyle: ['dulce', 'fresco'],
    projections: ['high'],
  },

  {
    name: 'Club de Nuit Intense Man',
    brand: 'Armaf',
    family: 'Amaderado Aromático',
    match: 'El Aventus killer. +50.000 vendidos. El masculino árabe más popular de Argentina.',
    description: 'Limón, piña y abedul ahumado. El "Aventus" accesible. La fragancia de liderazgo más copiada del mundo.',
    exhaustiveDescription: 'Club de Nuit Intense Man es quizás la fragancia más influyente del siglo XXI a precio democrático. Su apertura cítrico-frutal de limón brillante y piña exuberante es imbatible. El corazón de abedul ahumado y base de pachuli la hace letalmente eficaz en el ámbito corporativo.',
    sommelier: 'Club de Nuit Intense Man tiene más de 50.000 unidades vendidas en MercadoLibre Argentina — es el perfume árabe masculino más popular del país. Es el perfume que usás cuando querés que sepan que llegaste antes de abrir la puerta.',
    occasion: 'Noche · Eventos · Trabajo',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno · Primavera',
    vibe: 'Elegante · Poderoso · Masculino',
    image: '/perfumes/clubdenuit-intense.webp',
    topNotes: ['Piña', 'Bergamota', 'Manzana', 'Abedul'],
    heartNotes: ['Rosa', 'Jazmín', 'Pachulí'],
    baseNotes: ['Almizcle', 'Ámbar', 'Vetiver'],
    notes: ['Piña', 'Abedul', 'Pachulí', 'Vetiver', 'Ámbar'],
    costUSDT: 35.5,
    priceARS: 68000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+50000 vendidos ML AR — top masculino árabe',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial', 'oficina_diario'],
    seasons: ['fall', 'winter', 'spring'],
    scentStyle: ['fresco', 'maderoso'],
    projections: ['beast'],
  },

  {
    name: '9PM',
    brand: 'Afnan Perfumes',
    family: 'Oriental Vainilla',
    match: 'El clon árabe del Ultra Male de JPG. Beast Mode nocturno.',
    description: 'Manzana, lavanda, canela, vainilla y tonka bean crean la vibración nocturna más lograda. Irresistible desde las 9 PM.',
    exhaustiveDescription: 'Afnan 9 PM es el guardián de la noche en el universo de la perfumería moderna. Eleva la fórmula golosa con manzana más jugosa, lavanda más profunda y una canela que quema con delicadeza. El corazón de vainilla y tonka bean es pura seducción magnética.',
    sommelier: '9PM de Afnan es el favorito masculino nocturno de Argentina. Dulce, potente y con proyección extrema — lo llaman el clon del Ultra Male de Jean Paul Gaultier. Proyección extrema: se percibe antes de que entrés y permanece mucho después de que te fuiste.',
    occasion: 'Noche · Salidas · Eventos',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Seductor · Dulce · Potente',
    image: '/perfumes/afnan-9pm.webp',
    topNotes: ['Manzana', 'Canela', 'Lavanda', 'Bergamota'],
    heartNotes: ['Flor de azahar', 'Lirio de los valles'],
    baseNotes: ['Vainilla', 'Almizcle', 'Sándalo'],
    notes: ['Canela', 'Lavanda', 'Vainilla', 'Almizcle', 'Manzana'],
    costUSDT: 31.5,
    priceARS: 56000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+1000 vendidos ML AR',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['fall', 'winter'],
    scentStyle: ['dulce', 'especiado'],
    projections: ['beast'],
  },

  {
    name: 'Amber Oud Gold Edition',
    brand: 'Al Haramain',
    family: 'Amaderado Oriental',
    match: 'El árabe premium más destacado de Argentina. Lujo real.',
    description: 'Bergamota, notas verdes, melón y piña se fusionan con ámber solar y un almizcle imponente. Ícono de lujo accesible que conquista día y noche.',
    exhaustiveDescription: 'Amber Oud Gold Edition represents el cénit de la línea Amber Oud. Su apertura combina bergamota brillante, notas verdes frescas, melón jugoso y piña tropical en un acorde frutal de alta joyería. El corazón revela ámber solar dorado que evoluciona hacia una base de almizcle puro.',
    sommelier: 'Al Haramain es el árabe premium más destacado de Argentina según Nubimetrics. El oud auténtico árabe es rico y profundo — nada que ver con las versiones sintéticas europeas. Es el perfume que alguien compra en Dubai y después busca de dónde lo consiguió.',
    occasion: 'Eventos · Noche · Ocasiones especiales',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Lujoso · Profundo · Premium',
    image: '/perfumes/amber-oud-gold.edition.webp',
    topNotes: ['Bergamota', 'Piña tropical', 'Notas verdes'],
    heartNotes: ['Oud árabe', 'Rosa', 'Jazmín'],
    baseNotes: ['Ámbar solar', 'Sándalo dorado', 'Almizcle'],
    notes: ['Oud', 'Bergamota', 'Ámbar', 'Sándalo', 'Rosa'],
    costUSDT: 46,
    priceARS: 85000,
    inStock: true,
    deliveryDays: 'mismo día',
    tier: 1,
    mlSales: '+1000 vendidos ML AR — top unisex premium AR',
    gender: 'unisex',
    occasions: ['evento_especial', 'cita_nocturna'],
    seasons: ['fall', 'winter'],
    scentStyle: ['maderoso', 'especiado'],
    projections: ['beast'],
  },

  // ═══════════════════════════════════════════════════
  // TIER 2 — POR ENCARGO (inStock: false)
  // ═══════════════════════════════════════════════════

  {
    name: 'Fakhar Black',
    brand: 'Lattafa Perfumes',
    family: 'Oriental Especiado Amaderado',
    match: 'Masculino de autor. Cuero, pimienta y maderas nobles.',
    description: 'Especiado y sofisticado. Pimienta rosa, cardamomo y cuero.',
    exhaustiveDescription: 'Fakhar Black es el perfume para el hombre que no necesita explicaciones. La pimienta rosa y el cardamomo abren con una especiería elegante — el cuero y el ladano de la base crean una profundidad que es difícil de ignorar.',
    sommelier: 'Fakhar Black no es para todos: es para los que saben lo que quieren. Pimienta, cuero y maderas oscuras — un perfume que comunica carácter antes de que digas una palabra.',
    occasion: 'Noche · Eventos',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno',
    vibe: 'Oscuro · Sofisticado · Masculino',
    image: '/perfumes/fakhar-black.webp',
    topNotes: ['Pimienta rosa', 'Pomelo', 'Cardamomo'],
    heartNotes: ['Cuero', 'Nardos', 'Notas solares'],
    baseNotes: ['Ladano', 'Ámbar', 'Cachemira'],
    notes: ['Pimienta', 'Cuero', 'Ladano', 'Ámbar', 'Cardamomo'],
    costUSDT: 28.5,
    priceARS: 56000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['high'],
  },

  {
    name: 'Badee Al Oud Negro',
    brand: 'Lattafa Perfumes',
    family: 'Amaderado Oriental',
    match: 'Oud puro. Para los que buscan intensidad y sofisticación árabe.',
    description: 'Oud, cedro y rosa. La esencia del oud árabe modernizado.',
    exhaustiveDescription: 'Badee Al Oud negro es para el que quiere la experiencia oud sin concesiones. Profundo, amaderado y con una proyección que llena el ambiente.',
    sommelier: 'Badee Al Oud negro es oud en estado puro. Serio, profundo y amaderado — el perfume para el que quiere dejar huella donde va. Una de las fragancias más referenciadas en las guías de perfumería árabe 2026.',
    occasion: 'Noche · Eventos especiales',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno',
    vibe: 'Profundo · Intenso · Árabe clásico',
    image: '/perfumes/badee-al-oud-negro.webp',
    topNotes: ['Rosa', 'Lichi', 'Manzana'],
    heartNotes: ['Oud', 'Cedro', 'Ciruela'],
    baseNotes: ['Vainilla', 'Musgo', 'Pachulí'],
    notes: ['Oud', 'Cedro', 'Rosa', 'Pachulí', 'Vainilla'],
    costUSDT: 28,
    priceARS: 55000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['fall', 'winter'],
    scentStyle: ['maderoso', 'especiado'],
    projections: ['high'],
  },

  {
    name: 'Salvo Intense',
    brand: 'Maison Alhambra',
    family: 'Oriental Especiado',
    match: 'El más versátil. Cítrico, especiado y elegante para cualquier ocasión.',
    description: 'Bergamota, cardamomo y cedro. Todo uso, toda estación.',
    exhaustiveDescription: 'Salvo Intense de Maison Alhambra es el perfume árabe para quien no quiere equivocarse. Versátil, elegante y con una duración impresionante para su precio.',
    sommelier: 'Salvo Intense es el todoterreno del catálogo — funciona para el trabajo, para una salida y para el día a día. Cítrico en la apertura, especiado en el corazón, amaderado en la base. El perfume árabe recomendado para quien quiere empezar en el mundo de las fragancias árabes.',
    occasion: 'Día · Trabajo · Todo uso',
    longevity: '8-10h',
    sillage: 'Media-Alta',
    season: 'Todo el año',
    vibe: 'Versátil · Fresco · Elegante',
    image: '/perfumes/salvo-intense.webp',
    topNotes: ['Bergamota', 'Lima', 'Cardamomo'],
    heartNotes: ['Rosa', 'Jazmín', 'Pimienta'],
    baseNotes: ['Cedro', 'Almizcle', 'Ámbar'],
    notes: ['Bergamota', 'Cardamomo', 'Rosa', 'Cedro', 'Almizcle'],
    costUSDT: 24.5,
    priceARS: 50000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'masculino',
    occasions: ['oficina_diario', 'evento_especial', 'deporte_aire_libre'],
    seasons: ['summer', 'winter', 'spring', 'fall'],
    scentStyle: ['fresco', 'especiado'],
    projections: ['moderate', 'high'],
  },

  {
    name: 'Asad',
    brand: 'Lattafa Perfumes',
    family: 'Amaderado Especiado',
    match: 'El rey indiscutido de los masculinos árabes 2026.',
    description: 'Pimienta negra, piña, tabaco y café con base de pachuli y sándalo. La bestia oscura del catálogo árabe.',
    exhaustiveDescription: 'Asad ("León" en árabe) vive a la altura de su nombre. La apertura de pimienta negra y piña crea una tensión magnética entre especias y dulzura. El corazón de tabaco curado y café espresso añade una dimensión oscura que pocos se atreven a explorar.',
    sommelier: 'Asad de Lattafa es el masculino árabe más recomendado de 2026 — mencionado en todas las guías como el "todoterreno definitivo". Amaderado especiado con un drydown que es pura adicción. Si probás uno solo, que sea este.',
    occasion: 'Trabajo · Noche · Todo uso',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno · Primavera',
    vibe: 'Poderoso · Masculino · Adictivo',
    image: '/perfumes/lattafa-asad.webp',
    topNotes: ['Bergamota', 'Lavanda', 'Cardamomo'],
    heartNotes: ['Cedro', 'Pachulí', 'Vetiver'],
    baseNotes: ['Oud', 'Almizcle', 'Ámbar'],
    notes: ['Cedro', 'Pachulí', 'Oud', 'Almizcle', 'Lavanda'],
    costUSDT: 28,
    priceARS: 57000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+1000 vendidos ML AR',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial', 'oficina_diario'],
    seasons: ['fall', 'winter', 'spring'],
    scentStyle: ['maderoso', 'especiado'],
    projections: ['high'],
  },

  {
    name: 'Yara Elixir',
    brand: 'Lattafa Perfumes',
    family: 'Oriental Gourmand',
    match: 'La versión premium e intensa de la familia Yara.',
    description: 'Más profundo y oscuro que Yara. Oud, vainilla y especias orientales.',
    exhaustiveDescription: 'Yara Elixir es la evolución nocturna de la familia Yara. Conserva el ADN dulce pero añade profundidad oud y especias que lo transforman en algo completamente diferente y más sofisticado.',
    sommelier: 'Yara Elixir toma todo lo que amás de Yara y lo intensifica. Más oscuro, más profundo, más duradero. Para la que ya conoce Yara y quiere algo con más carácter para las noches.',
    occasion: 'Noche · Eventos',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno',
    vibe: 'Profundo · Dulce · Intenso',
    image: '/perfumes/yara-elixir.webp',
    topNotes: ['Frutos rojos', 'Bergamota', 'Mandarina'],
    heartNotes: ['Rosa', 'Oud', 'Especias'],
    baseNotes: ['Vainilla', 'Almizcle', 'Ámbar'],
    notes: ['Oud', 'Vainilla', 'Rosa', 'Almizcle', 'Frutos rojos'],
    costUSDT: 28.5,
    priceARS: 56000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'femenino',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['fall', 'winter'],
    scentStyle: ['dulce', 'especiado'],
    projections: ['high'],
  },

  {
    name: 'Badee Al Oud Rosado',
    brand: 'Lattafa Perfumes',
    family: 'Floral Oriental',
    match: 'La versión femenina del oud árabe. Elegancia floral con profundidad.',
    description: 'Rosa, oud y vainilla. Femenino con carácter árabe.',
    exhaustiveDescription: 'Badee Al Oud rosado combina la elegancia floral con la profundidad del oud árabe. Es el equilibrio perfecto entre un perfume femenino occidental y la intensidad árabe.',
    sommelier: 'Badee Al Oud rosado es el oud femenino por excelencia. Rosa y oud en perfecto equilibrio — floral sin ser superficial, árabe sin ser abrumador. Para la que quiere algo diferente y sofisticado.',
    occasion: 'Eventos · Noche',
    longevity: '8-10h',
    sillage: 'Media-Alta',
    season: 'Primavera · Otoño',
    vibe: 'Floral · Profundo · Elegante',
    image: '/perfumes/badee-al-oud-rosado.webp',
    topNotes: ['Rosa', 'Frutas rosadas', 'Bergamota'],
    heartNotes: ['Oud', 'Jazmín', 'Iris'],
    baseNotes: ['Vainilla', 'Almizcle', 'Madera'],
    notes: ['Rosa', 'Oud', 'Jazmín', 'Vainilla', 'Almizcle'],
    costUSDT: 26,
    priceARS: 53000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'femenino',
    occasions: ['evento_especial', 'cita_nocturna'],
    seasons: ['spring', 'fall'],
    scentStyle: ['dulce', 'maderoso'],
    projections: ['moderate', 'high'],
  },

  {
    name: 'Fakhar Rose',
    brand: 'Lattafa Perfumes',
    family: 'Floral Oriental',
    match: "Inspirado en L'Interdit de Givenchy. Femenino y envolvente.",
    description: 'Naranja, jazmín y vetiver. Elegancia femenina árabe.',
    exhaustiveDescription: "Fakhar Rose de Lattafa está inspirado en L'Interdit de Givenchy pero con la concentración y duración características de la perfumería árabe. Floral, femenino y con una base de vetiver que le da profundidad.",
    sommelier: 'Fakhar Rose es el perfume para la que quiere el lujo de Givenchy a una fracción del precio. Floral elegante con una base amaderada que lo hace memorable. El tipo de perfume que usás a una reunión importante.',
    occasion: 'Eventos · Trabajo · Ocasiones especiales',
    longevity: '8-10h',
    sillage: 'Media',
    season: 'Primavera · Verano',
    vibe: 'Floral · Elegante · Femenino',
    image: '/perfumes/fakhar-rose.webp',
    topNotes: ['Naranja', 'Flor de azahar', 'Bergamota'],
    heartNotes: ['Jazmín', 'Tuberosa', 'Rosa'],
    baseNotes: ['Vetiver', 'Pachulí', 'Almizcle'],
    notes: ['Rosa', 'Jazmín', 'Naranja', 'Vetiver', 'Pachulí'],
    costUSDT: 27.5,
    priceARS: 53000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'femenino',
    occasions: ['evento_especial', 'oficina_diario'],
    seasons: ['spring', 'summer'],
    scentStyle: ['dulce', 'fresco'],
    projections: ['moderate'],
  },

  {
    name: 'Asad Bourbon',
    brand: 'Lattafa Perfumes',
    family: 'Oriental Gourmand Amaderado',
    match: 'Asad con un giro oscuro de bourbon y vainilla. Para coleccionistas.',
    description: 'Lavanda y pimienta negra que abren un corazón de coco y sal marina. Un fondo de vainilla suntuosa que evoca el viejo dinero.',
    exhaustiveDescription: 'Asad Bourbon transporta al explorador sophisticated a un universo de calidez y prestigio. La apertura combina lavanda aromática con cardamomo audaz, resolviendo en un corazón terroso. La base de vainilla bourbon suntuosa ancla la composición.',
    sommelier: 'Asad Bourbon es lo que pasa cuando tomás el mejor masculino árabe y le agregás un trago de whisky. Bourbon, tabaco y maderas oscuras — para los que ya conocen Asad y quieren su versión más intensa y nocturna.',
    occasion: 'Noche · Eventos exclusivos',
    longevity: '10-12h',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Oscuro · Premium · Masculino intenso',
    image: '/perfumes/asad-bourbon-1.webp',
    topNotes: ['Bergamota', 'Especias', 'Cardamomo'],
    heartNotes: ['Bourbon', 'Cedro', 'Tabaco'],
    baseNotes: ['Oud', 'Vainilla', 'Almizcle oscuro'],
    notes: ['Bourbon', 'Tabaco', 'Oud', 'Cedro', 'Vainilla'],
    costUSDT: 31.5,
    priceARS: 58000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'masculino',
    occasions: ['cita_nocturna', 'evento_especial'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['beast'],
  },

  {
    name: 'Honor & Glory Blanco',
    brand: 'Lattafa Perfumes',
    family: 'Oriental Especiado',
    match: 'Opulento y sofisticado. Para quienes buscan profundidad y exclusividad.',
    description: 'Una declaración de poder olfativo. Oud oscuro y resinoso con madera de sándalo y almizcle que proclaman elegancia árabe auténtica.',
    exhaustiveDescription: "Honor & Glory es la cumbre de la línea Bade'e Al Oud. Una composición gourmand de alta joyería que abre con una explosión de piña dorada y caramelo brulee, revelando en su corazón una vainilla opulenta y musgo resinoso. Creado para celebraciones de lujo y momentos únicos, es la definición del prestigio olfativo árabe moderno.",
    sommelier: 'Honor & Glory Blanco es el perfume que impresiona a los conocedores. Piña y crème brûlée abren con elegancia — la cúrcuma y la canela del corazón añaden una especiería oriental única. Para el que quiere algo que nadie más tenga.',
    occasion: 'Eventos · Noche',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno',
    vibe: 'Sofisticado · Oriental · Exclusivo',
    image: '/perfumes/honor-glory.webp',
    topNotes: ['Piña', 'Crème brûlée', 'Bergamota'],
    heartNotes: ['Cúrcuma', 'Canela', 'Pimienta negra'],
    baseNotes: ['Benjuí', 'Ámbar', 'Almizcle'],
    notes: ['Piña', 'Cúrcuma', 'Canela', 'Benjuí', 'Ámbar'],
    costUSDT: 28.6,
    priceARS: 54000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+500 vendidos ML AR',
    gender: 'unisex',
    occasions: ['evento_especial', 'oficina_diario'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['high'],
  },

  {
    name: 'Fakhar Gold',
    brand: 'Lattafa Perfumes',
    family: 'Floral Oriental',
    match: 'Femenino premium. Elegancia árabe en versión dorada.',
    description: 'Floral especiado con base amaderada. La versión gold de Fakhar.',
    exhaustiveDescription: 'Fakhar Gold es la versión femenina más elegante de la línea Fakhar. Floral con especias orientales y una base amaderada que lo hace memorable y duradero.',
    sommelier: 'Fakhar Gold es el perfume de las ocasiones especiales femeninas. Floral sin ser simple, especiado sin ser abrumador — el equilibrio perfecto para la mujer que quiere ser recordada.',
    occasion: 'Eventos · Noche',
    longevity: '8-10h',
    sillage: 'Media-Alta',
    season: 'Otoño · Invierno',
    vibe: 'Dorado · Elegante · Premium',
    image: '/perfumes/fakhar-gold.webp',
    topNotes: ['Pimienta rosa', 'Pomelo', 'Bergamota'],
    heartNotes: ['Rosa', 'Jazmín', 'Iris'],
    baseNotes: ['Cedro', 'Almizcle', 'Ámbar'],
    notes: ['Rosa', 'Jazmín', 'Pimienta rosa', 'Cedro', 'Ámbar'],
    costUSDT: 27.5,
    priceARS: 53000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 2,
    mlSales: '+300 vendidos ML AR',
    gender: 'femenino',
    occasions: ['evento_especial', 'cita_nocturna'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['moderate', 'high'],
  },

  // ═══════════════════════════════════════════════════
  // TIER 3 — SOLO POR ENCARGO / NICHO
  // ═══════════════════════════════════════════════════

  {
    name: 'Badee Al Oud Rojo Sublime',
    brand: 'Lattafa Perfumes',
    family: 'Amaderado Frutal',
    match: 'La variante roja del oud árabe. Para quienes buscan algo diferente.',
    description: 'Manzana, lichi y oud. Una interpretación más frutal del oud.',
    exhaustiveDescription: 'Badee Al Oud Sublime (rojo) ofrece una interpretación más frutal y accesible del oud árabe clásico. La manzana y el lichi suavizan la intensidad del oud.',
    sommelier: 'Badee Al Oud Rojo Sublime es el oud para los que todavía no saben si les gusta el oud. La manzana y el lichi hacen que la entrada sea más amable, pero el oud del corazón está ahí — profundo y árabe.',
    occasion: 'Noche · Eventos',
    longevity: '10-12h',
    sillage: 'Alta',
    season: 'Otoño · Invierno',
    vibe: 'Frutal · Amaderado · Oriental',
    image: '/perfumes/badee-al-oud-rojo-sublime.webp',
    topNotes: ['Manzana', 'Lichi', 'Rosa'],
    heartNotes: ['Oud', 'Ciruela', 'Jazmín'],
    baseNotes: ['Vainilla', 'Musgo', 'Pachulí'],
    notes: ['Oud', 'Manzana', 'Lichi', 'Vainilla', 'Pachulí'],
    costUSDT: 28.5,
    priceARS: 55000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 3,
    mlSales: '+200 vendidos ML AR',
    gender: 'unisex',
    occasions: ['cita_nocturna'],
    seasons: ['fall', 'winter'],
    scentStyle: ['maderoso', 'especiado'],
    projections: ['high'],
  },

  {
    name: 'Club de Nuit Urban',
    brand: 'Armaf',
    family: 'Amaderado Aromático',
    match: 'La versión urbana y moderna del Club de Nuit clásico.',
    description: 'Más fresco y moderno que el Intense. Para el día a día.',
    exhaustiveDescription: 'Club de Nuit Urban toma el DNA del CDNI y lo adapta para un uso más diurno y urbano. Menos intenso, más versátil.',
    sommelier: 'Club de Nuit Urban es para quien ama el CDNI pero lo quiere para el trabajo. Misma elegancia de la familia, con menos proyección y más versatilidad diurna.',
    occasion: 'Trabajo · Día · Casual',
    longevity: '8-10h',
    sillage: 'Media',
    season: 'Primavera · Otoño',
    vibe: 'Urbano · Moderno · Versátil',
    image: '/perfumes/club-de-nuit-urban.webp',
    topNotes: ['Bergamota', 'Pomelo', 'Piña'],
    heartNotes: ['Rosa', 'Jazmín', 'Cedro'],
    baseNotes: ['Almizcle', 'Vetiver', 'Ámbar'],
    notes: ['Bergamota', 'Piña', 'Cedro', 'Vetiver', 'Almizcle'],
    costUSDT: 33.5,
    priceARS: 63000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 3,
    mlSales: '+200 vendidos ML AR',
    gender: 'masculino',
    occasions: ['evento_especial', 'oficina_diario', 'deporte_aire_libre'],
    seasons: ['spring', 'fall'],
    scentStyle: ['fresco', 'maderoso'],
    projections: ['moderate'],
  },

  {
    name: 'Odyssey Candee',
    brand: 'Armaf',
    family: 'Floral Frutal Dulce',
    match: 'Special Edition. Dulce, juvenil y con mucha proyección.',
    description: 'Frutal dulce femenino. Edición especial de Odyssey.',
    exhaustiveDescription: 'Odyssey Candee de Armaf Special Edition es un perfume femenino frutal y dulce con la calidad de proyección característica de Armaf. Juvenil y alegre.',
    sommelier: 'Odyssey Candee Special Edition es para la que quiere algo dulce, frutal y diferente. La proyección de Armaf con un perfil más jovial y fresco. Perfecto para el verano y la primavera.',
    occasion: 'Día · Salidas casuales',
    longevity: '6-8h',
    sillage: 'Media',
    season: 'Primavera · Verano',
    vibe: 'Dulce · Juvenil · Fresco',
    image: '/perfumes/odyssey-candee.webp',
    topNotes: ['Mandarina', 'Frutas tropicales', 'Bergamota'],
    heartNotes: ['Flor de azahar', 'Rosa', 'Jazmín'],
    baseNotes: ['Almizcle', 'Sándalo', 'Vainilla'],
    notes: ['Mandarina', 'Frutas tropicales', 'Rosa', 'Almizcle', 'Vainilla'],
    costUSDT: 26.5,
    priceARS: 50000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 3,
    mlSales: '+200 vendidos ML AR',
    gender: 'femenino',
    occasions: ['evento_especial', 'oficina_diario', 'deporte_aire_libre'],
    seasons: ['spring', 'summer'],
    scentStyle: ['dulce', 'fresco'],
    projections: ['moderate'],
  },

  {
    name: 'Mandarin Sky Elixir',
    brand: 'Armaf',
    family: 'Oriental Amaderado',
    match: 'La versión premium e intensa de Mandarin Sky. Para coleccionistas.',
    description: 'Más profundo y especiado que el Mandarin Sky original.',
    exhaustiveDescription: 'Mandarin Sky Elixir toma el DNA tropical del original y lo profundiza con especias orientales y maderas oscuras. Una experiencia más compleja y sofisticada.',
    sommelier: 'Mandarin Sky Elixir es para el que ya tiene el Mandarin Sky original y quiere ir un paso más allá. Más profundo, más especiado, más nocturno. Para los conocedores de Armaf.',
    occasion: 'Noche · Eventos especiales',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Profundo · Premium · Oriental',
    image: '/perfumes/mandarin-sky-elixir.webp',
    topNotes: ['Mandarina', 'Especias', 'Bergamota'],
    heartNotes: ['Oud', 'Sándalo', 'Rosa'],
    baseNotes: ['Ámbar', 'Almizcle oscuro', 'Vetiver'],
    notes: ['Mandarina', 'Oud', 'Sándalo', 'Ámbar', 'Especias'],
    costUSDT: 43.5,
    priceARS: 80000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 3,
    mlSales: '+100 vendidos ML AR',
    gender: 'unisex',
    occasions: ['evento_especial', 'cita_nocturna'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['beast'],
  },

  {
    name: 'Mandarin Sky Vintage',
    brand: 'Armaf',
    family: 'Oriental Amaderado',
    match: 'Edición vintage exclusiva. La versión más densa y opulenta de la familia.',
    description: 'El Mandarin Sky más oscuro y complejo. Para ocasiones únicas.',
    exhaustiveDescription: 'Mandarin Sky Vintage es la cima de la línea Mandarin Sky de Armaf. Rico, opulento y con una complejidad que requiere tiempo para entender. Para los que quieren lo mejor de lo mejor.',
    sommelier: 'Mandarin Sky Vintage es el perfume que guardás para las ocasiones que importan. La versión más compleja, más rica y más opulenta de la familia — un perfume que se descubre lentamente durante las horas que lo usás.',
    occasion: 'Eventos exclusivos · Noche',
    longevity: '12h+',
    sillage: 'Beast Mode',
    season: 'Otoño · Invierno',
    vibe: 'Opulento · Complejo · Exclusivo',
    image: '/perfumes/mandarin-sky-vintage.webp',
    topNotes: ['Mandarina', 'Especias orientales', 'Azafrán'],
    heartNotes: ['Oud premium', 'Rosa damascena', 'Pachulí'],
    baseNotes: ['Ámbar gris', 'Sándalo', 'Almizcle'],
    notes: ['Oud', 'Azafrán', 'Mandarina', 'Ámbar gris', 'Sándalo'],
    costUSDT: 45,
    priceARS: 82000,
    inStock: false,
    deliveryDays: '5-8 días hábiles',
    tier: 3,
    mlSales: '+100 vendidos ML AR',
    gender: 'unisex',
    occasions: ['evento_especial', 'cita_nocturna'],
    seasons: ['fall', 'winter'],
    scentStyle: ['especiado', 'maderoso'],
    projections: ['beast'],
  },

]
